d_b - d_a \leq 2
d_c - d_a \leq 3
d_d - d_a \leq 8
d_h - d_a \leq 9
d_a - d_b \leq 4
d_c - d_b \leq 5
d_e - d_b \leq 7
d_f - d_b \leq 4
d_d - d_c \leq 10
d_b - d_c \leq 5
d_g - d_c \leq 9
d_i - d_c \leq 11
d_f - d_c \leq 4
d_a - d_d \leq 8
d_g - d_d \leq 2
d_j - d_d \leq 5
d_f - d_d \leq 1
d_h - d_e \leq 5
d_c - d_e \leq 4
d_i - d_e \leq 10
d_i - d_f \leq 2
d_g - d_f \leq 2
d_d - d_g \leq 2
d_j - d_g \leq 8
d_k - d_g \leq 12
d_i - d_h \leq 5
d_k - d_h \leq 10
d_a - d_i \leq 20
d_k - d_i \leq 6
d_j - d_i \leq 2
d_m - d_i \leq 12
d_i - d_j \leq 2
d_k - d_j \leq 4
d_l - d_j \leq 5
d_h - d_k \leq 10
d_m - d_k \leq 10
d_m - d_l \leq 2